"player": [
        {
            "idPlayer": "34153736",
            "idTeam": "137235",
            "idTeam2": "0",
            "idTeamNational": null,
            "idSoccerXML": "0",
            "idAPIfootball": null,
            "idPlayerManager": null,
            "strNationality": "USA",
            "strPlayer": "Kobe Bryant",
            "strPlayerAlternate": null,
            "strTeam": "_Deceased Basketball",
            "strTeam2": "",
            "strSport": "Basketball",
            "intSoccerXMLTeamID": null,
            "dateBorn": "1978-08-23",
            "strNumber": "24",
            "dateSigned": null,
            "strSigning": "",
            "strWage": "",
            "strOutfitter": "",
            "strKit": "",
            "strAgent": "",
            "strBirthLocation": "Philadelphia, PA, USA",
            "strDescriptionEN": "Kobe Bean Bryant (August 23, 1978 – January 26, 2020) was an American professional basketball player. He played his entire 20-year career with the Los Angeles Lakers of the National Basketball Association (NBA). He entered the NBA directly from high school and won five NBA championships. Bryant is an 18-time All-Star, 15-time member of the All-NBA Team, 12-time member of the All-Defensive team and was the NBA's Most Valuable Player (MVP) in 2008. Widely regarded as one of the greatest basketball players of all time, he led the NBA in scoring during two seasons, ranks fourth on the league's all-time regular season scoring and fourth on the all-time postseason scoring list. Bryant is the first guard in NBA history to play at least 20 seasons.\r\n\r\nBryant is the son of former NBA player Joe Bryant. He enjoyed a successful high school basketball career at Lower Merion High School in Pennsylvania, where he was recognized as the top high school basketball player in the country. Upon graduation, he declared for the 1996 NBA draft and was selected by the Charlotte Hornets with the 13th overall pick; the Hornets then traded him to the Lakers. As a rookie, Bryant earned himself a reputation as a high-flyer and a fan favorite by winning the 1997 Slam Dunk Contest, and he was named an All-Star by his second season. Despite a feud between the two players, Bryant and Shaquille O'Neal led the Lakers to three consecutive NBA championships from 2000 to 2002.\r\n\r\nIn 2003, Bryant was accused of sexual assault, but the charges were eventually dropped and a civil suit was settled out of court. After the Lakers lost the 2004 NBA Finals, O'Neal was traded to the Miami Heat and Bryant became the cornerstone of the Lakers. He led the NBA in scoring during the 2005–06 and 2006–07 seasons. In 2006, he scored a career-high 81 points against the Toronto Raptors, the second most points scored in a single game in league history behind Wilt Chamberlain's 100-point game in 1962. Bryant was awarded the regular season's Most Valuable Player Award (MVP) in 2008. After the Lakers lost in the 2008 NBA Finals, Bryant led the team to two consecutive championships in 2009 and 2010, earning the Finals MVP Award on both occasions. He continued to be among the top players in the league through 2013, when he suffered a torn Achilles tendon at age 34. Although he recovered from that injury, he suffered season-ending injuries to his knee and shoulder, respectively, in the following two seasons. Citing his physical decline, Bryant retired after the 2015–16 season.\r\n\r\nAt 34 years and 104 days of age, Bryant became the youngest player in league history to reach 30,000 career points. He became the all-time leading scorer in Lakers franchise history on February 1, 2010 when he surpassed Jerry West. During his third year in the league, Bryant was chosen to start the All-Star Game, and he would continue to be selected to start that game for a record 18 consecutive appearances until his retirement. His four All-Star MVP Awards are tied with Bob Pettit for the most in NBA history. At the 2008 and 2012 Summer Olympics, he won gold medals as a member of the U.S. national team. In 2018, Bryant won the Academy Award for Best Animated Short Film for his film Dear Basketball. He died on January 26, 2020, in a helicopter crash outside of Calabasas, California, at the age of 41.",
            "strDescriptionDE": null,
            "strDescriptionFR": null,
            "strDescriptionCN": null,
            "strDescriptionIT": null,
            "strDescriptionJP": null,
            "strDescriptionRU": null,
            "strDescriptionES": "Kobe Bean Bryant (Filadelfia, 23 de agosto de 1978) es un exjugador estadounidense de baloncesto que disputó 20 temporadas en la NBA, todas ellas en Los Angeles Lakers, desde 1996 hasta 2016. Es hijo del también exjugador de la NBA Joe Bryant.\r\n\r\nCharlotte Hornets seleccionó a Bryant —procedente del instituto Lower Merion de Filadelfia— en el draft de la NBA de 1996, pero la franquicia lo traspasó inmediatamente a Los Angeles Lakers. Junto con Shaquille O'Neal, Bryant llevó a su equipo a la consecución de tres campeonatos de la NBA entre 2000 y 2002. Tras la marcha de O'Neal, lideró la clasificación de máximos anotadores de la liga en 2006 y 2007 y logró varios récords en ese periodo. En 2006 logró 81 puntos ante Toronto Raptors, la segunda mejor anotación de la historia por detrás de los 100 puntos de Wilt Chamberlain en 1962. El 7 de mayo de 2008 fue nombrado MVP de la temporada 2007-08 de la NBA. Después de perder las Finales de 2008, llevó a los Lakers a la obtención de otros dos títulos consecutivos en 2009 y 2010, donde ganó en ambas ocasiones el Premio Bill Russell al MVP de las Finales de la NBA.\r\n\r\nEs en la actualidad el tercer máximo anotador de la historia de la NBA, sólo superado por Kareem Abdul Jabbar y Karl Malone. Bryant es, empatado con Karl Malone, el jugador que más veces ha sido elegido en el Mejor Quintento de la temporada, con once ocasiones, y el segundo con más selecciones 18, para jugar el All-Star Game de la NBA, sólo por detrás de Kareem Abdul-Jabbar 19.\r\n\r\nPor contra, los más críticos alegan los bajos porcentajes de tiro de campo, tanto de dos como de tres puntos (a lo largo de su carrera promedió un 44% en tiros de dos y 33% en triples, que incluso bajan en playoffs), pues Kobe Bryant ha sido el jugador con más tiros fallados en toda la Historia de la NBA: 14.481 tiros de campo errados en temporada regular (anotó 11.719 de un total de 26.200 lanzamientos) y 2.485 (anotó 2.014 de un total de 4.499 lanzamientos) en playoffs, para un total de 16.966 tiros de campo fallados.\r\n\r\nSe retiró el 13 de abril de 2016, al final de la temporada regular, donde su equipo no clasificó para los playoffs, en un partido histórico con 60 puntos en su conteo, siendo un récord histórico para un jugador en el partido de su retiro. Los 60 de esa noche fue el record de puntos anotados en un partido en esa temporada, superando a Anthony Davis por tan solo un punto.",
            "strDescriptionPT": null,
            "strDescriptionSE": null,
            "strDescriptionNL": null,
            "strDescriptionHU": null,
            "strDescriptionNO": null,
            "strDescriptionIL": null,
            "strDescriptionPL": null,
            "strGender": "Male",
            "strSide": "",
            "strPosition": "Shooting Guard",
            "strCollege": null,
            "strFacebook": "www.facebook.com/Kobe/",
            "strWebsite": "",
            "strTwitter": "twitter.com/kobebryant",
            "strInstagram": "www.instagram.com/kobebryant",
            "strYoutube": "",
            "strHeight": "6 ft 6 in (1.98 m)",
            "strWeight": "212 lb (96 kg)",
            "intLoved": "3",
            "strThumb": "https://www.thesportsdb.com/images/media/player/thumb/ibdm881526808525.jpg",
            "strCutout": "https://www.thesportsdb.com/images/media/player/cutout/rqrmb61602281225.png",
            "strRender": "https://www.thesportsdb.com/images/media/player/render/bhon641580126129.png",
            "strBanner": "https://www.thesportsdb.com/images/media/player/banner/3rma0s1593092640.jpg",
            "strFanart1": "https://www.thesportsdb.com/images/media/player/fanart/uyuyww1422127945.jpg",
            "strFanart2": "https://www.thesportsdb.com/images/media/player/fanart/rvpqus1472157166.jpg",
            "strFanart3": "https://www.thesportsdb.com/images/media/player/fanart/rwypty1472157392.jpg",
            "strFanart4": "https://www.thesportsdb.com/images/media/player/fanart/xvvryv1472157262.jpg",
            "strCreativeCommons": "No",
            "strLocked": "unlocked"
        }
    ]
}